# Generated by Django 5.0.2 on 2024-02-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(null=True, upload_to='media/music'),
        ),
    ]
