# Generated by Django 5.0.2 on 2024-02-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(null=True, upload_to='madia/music'),
        ),
    ]
